### ISSUE TITLE
NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays

### ISSUE THREAD

**Issue by mrogowski** [mpi4py/shmem4py#2]
How should we handle this change in NumPy's behavior?

```
/shmem4py/test/test_rma.py:21: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint16 will fail in the future.
```

For most cases we can replace:
`self.assertEqual(val, np.array(-1, dtype=t))` with `self.assertEqual(val, np.array(-1).astype(t))` to keep the old behavior. Does that look good, @dalcinl?

How should we handle the case when `shmem.array()` gets a negative value with an unsigned data type? Should we mirror NumPy's behavior and throw a warning for now?

**Comment by dalcinl** [comment]
> `np.array(-1).astype(t)`

Yes, that's the proper fix.




> How should we handle the case when `shmem.array()` gets a negative value with an unsigned data type?

Maybe do nothing? Look at the code, NumPy will do the work for us.

**Comment by mrogowski** [comment]
Fixed in https://github.com/mpi4py/shmem4py/commit/f79cf38d570b7b843c58baceae6d956971c0c6b7.
